version: "3"
services:
  blockgametracker:
    build: .
    image: ghcr.io/clrxbl/blockgametracker
    environment:
      CONFIG_FILE: "/config/servers.yaml"
    volumes:
      - ./deploy/config:/config
