version: "3"
services:
  blockgametracker:
    build: .
    image: ghcr.io/clrxbl/blockgametracker
    environment:
      CONFIG_FILE: "kustomize/base/config/servers.yaml
    volumes:
      - /artifacts/gs8ksoo8oosssk04gkcsccos/deploy/config/servers.yaml
